{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: openai in /Users/blamy/Library/Python/3.9/lib/python/site-packages (0.26.3)\n",
      "Collecting openai\n",
      "  Using cached openai-0.26.4.tar.gz (55 kB)\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/normal/lib/python3.9/site-packages\n",
      "  sysconfig: /Library/Python/3.9/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/normal/lib/python3.9/site-packages\n",
      "  sysconfig: /Library/Python/3.9/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/normal'\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/overlay/lib/python3.9/site-packages\n",
      "  sysconfig: /Library/Python/3.9/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/overlay/lib/python3.9/site-packages\n",
      "  sysconfig: /Library/Python/3.9/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-build-env-cbfsm0q5/overlay'\u001b[0m\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/tmp_qcdu2t3\n",
      "       cwd: /private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16\n",
      "  Complete output (81 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 419, in _parse_attr\n",
      "      return getattr(StaticModule(module_name), attr_name)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 26, in __init__\n",
      "      spec = importlib.util.find_spec(name)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/util.py\", line 94, in find_spec\n",
      "      parent = __import__(parent_name, fromlist=['__path__'])\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/__init__.py\", line 9, in <module>\n",
      "      from openai.api_resources import (\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/__init__.py\", line 1, in <module>\n",
      "      from openai.api_resources.completion import Completion  # noqa: F401\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/completion.py\", line 4, in <module>\n",
      "      from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/abstract/__init__.py\", line 3, in <module>\n",
      "      from openai.api_resources.abstract.api_resource import APIResource\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/abstract/api_resource.py\", line 4, in <module>\n",
      "      from openai import api_requestor, error, util\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_requestor.py\", line 21, in <module>\n",
      "      import aiohttp\n",
      "  ModuleNotFoundError: No module named 'aiohttp'\n",
      "  \n",
      "  During handling of the above exception, another exception occurred:\n",
      "  \n",
      "  Traceback (most recent call last):\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py\", line 154, in get_requires_for_build_wheel\n",
      "      return self._get_build_requires(\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py\", line 135, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py\", line 150, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 3, in <module>\n",
      "      setup()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py\", line 153, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/_distutils/core.py\", line 121, in setup\n",
      "      dist.parse_config_files()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/dist.py\", line 798, in parse_config_files\n",
      "      parse_configuration(\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 158, in parse_configuration\n",
      "      meta.parse()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 498, in parse\n",
      "      section_parser_method(section_options)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 469, in parse_section\n",
      "      self[name] = value\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 222, in __setitem__\n",
      "      value = parser(value)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 597, in _parse_version\n",
      "      version = self._parse_attr(value, self.package_dir)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/config.py\", line 422, in _parse_attr\n",
      "      module = importlib.import_module(module_name)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n",
      "      return _bootstrap._gcd_import(name[level:], package, level)\n",
      "    File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 972, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "    File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
      "    File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "    File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "    File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
      "    File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
      "    File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/__init__.py\", line 9, in <module>\n",
      "      from openai.api_resources import (\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/__init__.py\", line 1, in <module>\n",
      "      from openai.api_resources.completion import Completion  # noqa: F401\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/completion.py\", line 4, in <module>\n",
      "      from openai.api_resources.abstract import DeletableAPIResource, ListableAPIResource\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/abstract/__init__.py\", line 3, in <module>\n",
      "      from openai.api_resources.abstract.api_resource import APIResource\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_resources/abstract/api_resource.py\", line 4, in <module>\n",
      "      from openai import api_requestor, error, util\n",
      "    File \"/private/var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/pip-install-il0yxn3r/openai_cc8ddc529a4447f58144f33d55564b16/openai/api_requestor.py\", line 21, in <module>\n",
      "      import aiohttp\n",
      "  ModuleNotFoundError: No module named 'aiohttp'\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[?25h\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/37/37/eea5ae693a9f95c554ba7665e96a105425d6823782105f2317cb8a2bb8be/openai-0.26.4.tar.gz#sha256=168813319a1422cb71a5005f9e404065483556cea52c9ccbfb838cda134087a7 (from https://pypi.org/simple/openai/) (requires-python:>=3.7.1). Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/yj/75gv77414dsd_3km1d4hs2l40000gn/T/tmp_qcdu2t3 Check the logs for full command output.\u001b[0m\n",
      "Requirement already satisfied: aiohttp in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from openai) (3.8.3)\n",
      "Requirement already satisfied: tqdm in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from openai) (4.64.1)\n",
      "Requirement already satisfied: requests>=2.20 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from openai) (2.28.2)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai) (2.1.1)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai) (1.26.14)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai) (2022.12.7)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from requests>=2.20->openai) (3.4)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (1.3.3)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (4.0.2)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (22.2.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (6.0.4)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (1.3.1)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in /Users/blamy/Library/Python/3.9/lib/python/site-packages (from aiohttp->openai) (1.8.2)\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.\n",
      "You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Requirement already satisfied: python-dotenv in /Users/blamy/Library/Python/3.9/lib/python/site-packages (0.21.1)\n",
      "\u001b[33mWARNING: You are using pip version 21.2.4; however, version 22.3.1 is available.\n",
      "You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.\u001b[0m\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "The dotenv extension is already loaded. To reload it, use:\n",
      "  %reload_ext dotenv\n"
     ]
    }
   ],
   "source": [
    "%pip install --upgrade openai\n",
    "%pip install python-dotenv\n",
    "%load_ext dotenv\n",
    "%dotenv"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{\n",
      "  \"choices\": [\n",
      "    {\n",
      "      \"finish_reason\": \"length\",\n",
      "      \"index\": 0,\n",
      "      \"logprobs\": null,\n",
      "      \"text\": \"\\n\\nOnce upon a time, there was a young girl named Rose. She lived in a small village in a faraway kingdom. Rose was a kind and gentle soul, and she was beloved by all who knew her.\\n\\nOne day, while walking in the woods near her home, she stumbled upon a beautiful pond. In the center of the pond was an enchanted castle, and while exploring, Rose noticed a small boat docked at the edge of the pond.\\n\\nCurious, Rose hopped in the boat and began rowing towards the castle. As she got closer, she noticed a small figure standing on the balcony of the castle. It was a fairy! The fairy waved her wand, and suddenly the waters of the pond began to sparkle with a thousand stars.\\n\\nThe fairy smiled at Rose and said, \\\"Welcome to my magical kingdom. I am here to grant you three wishes. Make them wisely, for they will come true!\\\"\\n\\nRose was overjoyed. She thought long and hard about her wishes. Finally, she wished for the world to be a kinder and more compassionate place, for all to be treated with respect and kindness, and for everyone to have enough food, shelter, and safety.\\n\\nThe fairy smiled\"\n",
      "    }\n",
      "  ],\n",
      "  \"created\": 1675042995,\n",
      "  \"id\": \"cmpl-6eDURJk9cDkqauUXMgtVnYL1hwchQ\",\n",
      "  \"model\": \"text-davinci-003\",\n",
      "  \"object\": \"text_completion\",\n",
      "  \"usage\": {\n",
      "    \"completion_tokens\": 256,\n",
      "    \"prompt_tokens\": 4,\n",
      "    \"total_tokens\": 260\n",
      "  }\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import openai\n",
    "\n",
    "openai.api_key = os.environ[\"OPENAI_API_KEY\"]\n",
    "\n",
    "response = openai.Completion.create(\n",
    "  model=\"text-davinci-003\",\n",
    "  prompt=\"Once Upon a time\",\n",
    "  temperature=0.7,\n",
    "  max_tokens=256,\n",
    "  top_p=1,\n",
    "  frequency_penalty=0,\n",
    "  presence_penalty=0\n",
    ")\n",
    "\n",
    "print(response)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
